### ISSUE TITLE
check penalty term in BIC in dealing with interactions

### ISSUE THREAD

**Issue by doughertyorama** [joetidwell/OCLO#7]
Check to make sure that the penalty term in the BIC appropriately penalizes model with interaction terms. inclusion of an interaction terms requires that the main effects are included in the model.

**Comment by joetidwell** [comment]
It doesn't. It should. Bug noted.

**Comment by joetidwell** [comment]
Fixed now. Modified `bicFit()`. This will probably slow down the algorithm a bit.
